[windows_servers:vars]
ansible_user=Administrateur_Du_Domaine_Ou_Local
ansible_password={{ lookup('env', 'ansible') }}
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
