[windows_servers:vars]
ansible_user=Administrator
ansible_password={{ lookup('env', 'ANSIBLE_PASSWORD') }}
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_transport=ntlm
