name: Installation Massive de l'Agent Zabbix

on:
  workflow_dispatch: # Permet le declenchement manuel en 1 clic depuis GitHub

jobs:
  install-zabbix:
    runs-on: self-hosted # Utilise votre runner local Ansible
    steps:
      - name: Recuperer le code du depot
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les extensions requises
        run: |
          pip install ansible pywinrm
          # Installation de la collection community.windows indispensable pour le pare-feu
          ansible-galaxy collection install community.windows

      - name: Lancer le deploiement Zabbix
        env:
          ANSIBLE_PASSWORD: ${{ secrets.WIN_SERVERS_PASSWORD }}
        run: |
          ansible-playbook -i inventory.ini deploy-zabbix.yml --forks 30
